language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tagarwal12/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tagarwal12/docker-react npm run test 